version: '3'

services:
  minio-server:
    image: quay.io/minio/minio
    container_name: minio-server
    environment:
      MINIO_ROOT_USER: "test"
      MINIO_ROOT_PASSWORD: "testpass"
      # Dedicated DNS
      MINIO_SERVER_URL: "http://minio.myapp.com"
      MINIO_BROWSER_REDIRECT_URL: "http://minio.myapp.com/minio/ui"
      # Subdomain
#      MINIO_SERVER_URL: "http://minio.myapp.com"
#      MINIO_BROWSER_REDIRECT_URL: "http://console.myapp.com"
    command: server --console-address ":9001" /data
    volumes:
      - minio-data:/data

  minio-client:
    build: .
    container_name: minio-client
    depends_on:
      - minio-server
    volumes:
      - ./target:/app/target
    command: ["java", "-jar", "/app/minio-example.jar"]

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/dedicated_dns/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - minio-server

volumes:
  minio-data:
